version: '3'
services:
  frontend:
    build: ./workflow-app  # Path to the Angular frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./workflow-api
    ports:
      - "3000:3000"
    env_file:
      - ./workflow-api/.env
    depends_on:
      - db
      - keycloak
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: budget_workflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: budget_workflow
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin       # Set admin username
      KEYCLOAK_ADMIN_PASSWORD: admin   # Set admin password
      PROXY_ADDRESS_FORWARDING: "true"
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
